org.gradle.jvmargs=-Xmx4G

available_loaders=fabric,forge,neoforge,tweaker

mod_version=1.17.0
maven_group=baritone
archives_base_name=baritone

java_version=25

minecraft_version=26.1

forge_version=62.0.9

neoforge_version=19-beta

fabric_version=0.18.6

nether_pathfinder_version=1.4.1

// These dependencies are used for common and tweaker
// while mod loaders usually ship their own version
mixin_version=0.8.7
asm_version=9.7
