org.gradle.jvmargs=-Xmx4G

available_loaders=fabric,forge,neoforge,tweaker

mod_version=1.18.0
maven_group=baritone
archives_base_name=baritone

java_version=25

minecraft_version=26.1.2

forge_version=64.0.11

neoforge_version=78

fabric_version=0.19.3

nether_pathfinder_version=1.6

// These dependencies are used for common and tweaker
// while mod loaders usually ship their own version
mixin_version=0.8.7
asm_version=9.7
