name: Bug Report
description: Report an issue or unexpected behavior that occurs within Baritone
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Issues are not a place to go ask support questions or start discussions. Please ask support questions or start discussions on the [Discord](http://discord.gg/s6fRBAUpmr).
  - type: textarea
    attributes:
      label: Describe The Bug
      description: A clear and concise description of what the bug is.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Minecraft Version
      description: Your current Minecraft version.
    validations:
      required: true
  - type: input
    attributes:
      label: Baritone Version
      description: Your current Baritone version (NOT YOUR MINECRAFT VERSION).
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: Your current operating system.
    validations:
      required: true
  - type: input
    attributes:
      label: Log File
      description: Your game's log file. DO NOT PASTE THE FILE CONTENTS! Copy the file from your file explorer and paste it. If you can't figure out how to do this, use a site like pastebin and include a URL.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
        - label: I know how to properly use check boxes.
          required: true
        - label: I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
          required: true
        - label: I have included logs, exceptions, and/or steps to reproduce the issue.
          required: true
        - label: I have not used any "OwO"s or "UwU"s in this issue.
          required: true
