name: Enhancement
description: Report a feature you would like to see in Baritone
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Issues are not a place to go ask support questions or start discussions. Please ask support questions or start discussions on the [Discord](http://discord.gg/s6fRBAUpmr).
  - type: textarea
    attributes:
      label: Describe the enhancement
      description: With as much detail as possible, describe what your suggestion would do for Baritone.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Settings
      description: If applicable, describe what settings/customizability should be offered to tweak the functionality of your suggestion.
    validations:
        required: false
  - type: textarea
    attributes:
      label: Context
      description: Describe how your suggestion would improve Baritone, or the reason behind it being added.
    validations:
        required: true
  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
        - label: I know how to properly use check boxes.
          required: true
        - label: I have not used any "OwO"s or "UwU"s in this issue.
          required: true
